spring:
    application:
        name: BillingModule
#                
# This configuration is the same for all the modules at the moment                
#
application:
    restTemplateConfig:
        readTimeout: 350
        connectTimeout: 550