spring:
    application:
        name: workflowmodule
        
jhipster:        
    registry:
        password: admin
        
#                
# This configuration is the same for all the modules at the moment                
#
application:
    restTemplateConfig:
        readTimeout: 350
        connectTimeout: 550